### ISSUE TITLE
CMake Error at CMakeLists.txt:8 (add_subdirectory):

### ISSUE THREAD

**Issue by Son1x90** [aroldanju/raptor-call-of-the-shadows#1]
Missing directories, most likely to missing readme file where the information should be?
It's not obvious where to get the files.

CMake Error at CMakeLists.txt:8 (add_subdirectory):
  add_subdirectory given source "vendor/ini" which is not an existing
  directory.

CMake Error at CMakeLists.txt:9 (add_subdirectory):
  add_subdirectory given source "vendor/res" which is not an existing
  directory.

CMake Error at CMakeLists.txt:10 (add_subdirectory):
  add_subdirectory given source "vendor/engine" which is not an existing
  directory.

**Comment by aroldanju** [comment]
Yes, I have to create a readme... In the meantime, these directories are as repositories in my profile **caengine**, **ini-reader** and **res-packager**.

**Comment by aroldanju** [comment]
I added a few instructions to Readme.md file to launch project.
