### ISSUE TITLE
Build fails with gcc10 fails in the linking stage

### ISSUE THREAD

**Issue by mnhauke** [aroldanju/raptor-call-of-the-shadows#2]
Build with gcc10 fails in the linking stage:
```
[    7s] [ 77%] Linking C executable ../raptor
[    7s] /usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/raptor.dir/game.c.o:(.bss+0x120): multiple definition of `G_DATA'; CMakeFiles/raptor.dir/bullet.c.o:(.bss+0x0): first defined here
[    7s] collect2: error: ld returned 1 exit status
```

gcc10 defaults to "-fno-common"
https://gcc.gnu.org/gcc-10/porting_to.html

Full buildlog:
[raptor-openSUSE-Tumbleweed-buildlog.txt](https://github.com/aroldanju/raptor-call-of-the-shadows/files/5792499/raptor-openSUSE-Tumbleweed-buildlog.txt)

**Comment by Frenzied-Pop** [comment]
I moved
`Data G_DATA;`
to main.c near the top, removed the other 2 declarations. got it to compile. 
It works! It put the executable in my home directory for some reason.

Also- it looks like the original developer is updating the game
https://www.patreon.com/scotthost

**Comment by kblaschke** [comment]
Changing line 26 in bullet.c to `extern Data G_DATA;` also does the trick.

**Comment by treloret** [comment]
Commenting it out in bullet.c also does the trick, since it's already declared as extern in the included data.h

**Comment by aroldanju** [comment]
Thank you! I removed it from bullet.c
